name: Run Selenium Automation

on:
  workflow_dispatch:  # Ye manually run karne ka option enable karega
  schedule:
    - cron: "0 12 * * *"  # Har din 12 PM UTC (India me 5:30 PM)

jobs:
  run-selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          wget https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-linux64.tar.gz
          tar -xvzf geckodriver-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Selenium Script
        env:
          LINKEDIN_EMAIL: ${{ secrets.LINKEDIN_EMAIL }}
          LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
          FILE_PATH: ${{ secrets.FILE_PATH }}
        run: |
          python linkedin_automation.py
