name: Run Selenium Daily

on:
  schedule:
    - cron: "0 12 * * *"  # Har din 12 PM UTC (India me 5:30 PM)
  workflow_dispatch:  # Isse aap manually bhi run kar sakenge

jobs:
  run-selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup Geckodriver (Firefox Driver)
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox-esr
          wget https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-v0.33.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.33.0-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/

      - name: Run Selenium script
        env:
          LINKEDIN_EMAIL: ${{ secrets.LINKEDIN_EMAIL }}
          LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
          FILE_PATH: ${{ secrets.FILE_PATH }}
        run: python linkedin_automation.py
